import type { FormDefinition } from "../types";
import { ESTADOS_CIVILES } from "@/lib/constants";

export const formB: FormDefinition = {
  code: "B",
  name: "Aviso de Accidente o Enfermedad",
  insurers: ["GNP", "ALLIANZ", "INBURSA", "SEGUROS MONTERREY"],
  autofill: {
    policy_number: "policy.policy_number",
    paternal_surname: "profile.paternal_surname",
    maternal_surname: "profile.maternal_surname",
    first_name: "profile.first_name",
    numero_certificado: "policy.numero_certificado",
    rfc: "profile.rfc",
    curp: "profile.curp",
    sex: "profile.sex",
    nationality: "profile.nationality",
    estado_civil: "profile.estado_civil",
    occupation: "profile.occupation",
    giro_negocio: "profile.giro_negocio",
    es_pep: "profile.es_pep",
    cargo_pep: "profile.cargo_pep",
    email: "profile.email",
    relationship_to_titular: "profile.relationship_to_titular",
    street: "profile.street",
    street_number: "profile.street_number",
    interior_number: "profile.interior_number",
    neighborhood: "profile.neighborhood",
    postal_code: "profile.postal_code",
    municipality: "profile.municipality",
    state: "profile.state",
    agente_nombre: "policy.agente_nombre",
    agente_clave: "policy.agente_clave",
    agente_telefono: "policy.agente_telefono",
    agente_estado: "policy.agente_estado",
  },
  sections: [
    {
      id: "encabezado",
      title: "Encabezado",
      fields: [
        { name: "policy_number", label: "Número de póliza", type: "text", required: true },
        { name: "fecha", label: "Fecha", type: "date", required: true },
      ],
    },
    {
      id: "asegurado_titular",
      title: "Datos del asegurado titular",
      fields: [
        { name: "paternal_surname", label: "Apellido Paterno", type: "text", required: true },
        { name: "maternal_surname", label: "Apellido Materno", type: "text" },
        { name: "first_name", label: "Nombre(s)", type: "text", required: true },
        { name: "numero_certificado", label: "Código Cliente / No. de Certificado", type: "text" },
        { name: "rfc", label: "RFC", type: "rfc", required: true },
        { name: "curp", label: "CURP", type: "curp", required: true },
        { name: "sex", label: "Género", type: "radio", required: true, options: [
          { value: "M", label: "Masculino" }, { value: "F", label: "Femenino" },
        ]},
        { name: "nationality", label: "Nacionalidad (si distinta a Mexicana)", type: "text" },
        { name: "estado_civil", label: "Estado civil", type: "radio", options: ESTADOS_CIVILES.map((o) => ({ value: o.value, label: o.label })) },
        { name: "occupation", label: "Ocupación actual", type: "text" },
        { name: "giro_negocio", label: "Actividad o giro del negocio", type: "text" },
        { name: "es_pep", label: "¿Desempeña o ha desempeñado cargo en gobierno en los últimos 4 años?", type: "radio", options: [
          { value: "si", label: "Sí" }, { value: "no", label: "No" },
        ]},
        { name: "cargo_pep", label: "Definir cargo", type: "text", showWhen: (d) => d.es_pep === "si" || d.es_pep === true },
        { name: "email", label: "Correo electrónico (opcional)", type: "email" },
        { name: "relationship_to_titular", label: "Relación con el Solicitante Titular", type: "text" },
      ],
    },
    {
      id: "contratante",
      title: "Contratante (Persona Moral, opcional)",
      fields: [
        { name: "razon_social", label: "Razón Social", type: "text" },
        { name: "codigo_cliente_pm", label: "Código Cliente", type: "text" },
        { name: "rfc_pm", label: "RFC", type: "rfc" },
        { name: "giro_pm", label: "Giro mercantil, actividad u objeto social", type: "text" },
        { name: "email_pm", label: "Correo o página de internet", type: "text" },
      ],
    },
    {
      id: "rep_legal",
      title: "Representante Legal",
      fields: [
        { name: "rep_paternal", label: "Apellido Paterno", type: "text" },
        { name: "rep_maternal", label: "Apellido Materno", type: "text" },
        { name: "rep_first_name", label: "Nombre(s)", type: "text" },
      ],
    },
    {
      id: "domicilio",
      title: "Domicilio particular",
      fields: [
        { name: "street", label: "Calle", type: "text", required: true },
        { name: "street_number", label: "Número exterior", type: "text" },
        { name: "interior_number", label: "Número interior", type: "text" },
        { name: "neighborhood", label: "Colonia", type: "text" },
        { name: "postal_code", label: "C.P.", type: "text" },
        { name: "municipality", label: "Municipio o Delegación", type: "text" },
        { name: "state", label: "Estado", type: "text" },
      ],
    },
    {
      id: "agente",
      title: "Datos del agente",
      fields: [
        { name: "agente_nombre", label: "Nombre del agente", type: "text" },
        { name: "agente_clave", label: "Clave", type: "text" },
        { name: "agente_telefono", label: "Teléfono", type: "tel" },
        { name: "agente_estado", label: "Estado", type: "text" },
      ],
    },
  ],
};
