// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "No autenticado" }],
    isError: true
  };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}
function errorResult(message) {
  return {
    content: [{ type: "text", text: message }],
    isError: true
  };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Qui\xE9n soy",
  description: "Devuelve el perfil, rol activo y roles del usuario conectado en CareCentral.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error: pErr }, { data: roles, error: rErr }] = await Promise.all([
      sb.from("profiles").select("full_name,email,active_role").eq("user_id", userId).maybeSingle(),
      sb.from("user_roles").select("role").eq("user_id", userId)
    ]);
    if (pErr) return errorResult(pErr.message);
    if (rErr) return errorResult(rErr.message);
    return jsonResult({
      user_id: userId,
      email: ctx.getUserEmail() ?? profile?.email,
      full_name: profile?.full_name,
      active_role: profile?.active_role,
      roles: (roles ?? []).map((r) => r.role)
    });
  }
});

// src/lib/mcp/tools/list-recetas.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var list_recetas_default = defineTool2({
  name: "list_recetas",
  title: "Listar recetas",
  description: "Lista recetas visibles para el usuario (paciente ve las suyas; m\xE9dico las que emiti\xF3). RLS aplica.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("M\xE1ximo de recetas (default 20)"),
    patient_id: z.string().uuid().optional().describe("Filtrar por paciente (opcional)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, patient_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("recetas").select("id,folio,patient_id,doctor_id,diagnostico,fecha_emision,estatus,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (patient_id) q = q.eq("patient_id", patient_id);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/get-receta.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_receta_default = defineTool3({
  name: "get_receta",
  title: "Obtener receta",
  description: "Devuelve la cabecera de una receta y todos sus renglones (medicamentos).",
  inputSchema: {
    receta_id: z2.string().uuid().describe("ID de la receta")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ receta_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const [{ data: receta, error: rErr }, { data: items, error: iErr }] = await Promise.all([
      sb.from("recetas").select("*").eq("id", receta_id).maybeSingle(),
      sb.from("receta_items").select("*").eq("receta_id", receta_id)
    ]);
    if (rErr) return errorResult(rErr.message);
    if (iErr) return errorResult(iErr.message);
    if (!receta) return errorResult("Receta no encontrada");
    return jsonResult({ receta, items });
  }
});

// src/lib/mcp/tools/list-pharmacy-catalog.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
var list_pharmacy_catalog_default = defineTool4({
  name: "list_pharmacy_catalog",
  title: "Cat\xE1logo de farmacia",
  description: "Lista SKUs del cat\xE1logo de farmacia (nombre, presentaci\xF3n, precio, categor\xEDa).",
  inputSchema: {
    q: z3.string().optional().describe("B\xFAsqueda por nombre"),
    only_active: z3.boolean().optional().describe("Solo activos (default true)"),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ q, only_active, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("pharmacy_catalog").select("id,sku,nombre,presentacion,categoria,precio_centavos,moneda,activo").order("nombre").limit(limit ?? 50);
    if (only_active !== false) query = query.eq("activo", true);
    if (q) query = query.ilike("nombre", `%${q}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-pharmacy-inventory.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
var list_pharmacy_inventory_default = defineTool5({
  name: "list_pharmacy_inventory",
  title: "Inventario de farmacia",
  description: "Devuelve el stock actual por SKU. \xDAtil para integraciones con ERP.",
  inputSchema: {
    limit: z4.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("pharmacy_inventory").select("catalog_id,stock_actual,stock_minimo,updated_at,catalog:pharmacy_catalog(sku,nombre,presentacion)").limit(limit ?? 100);
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-pharmacy-orders.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^4.4.3";
var list_pharmacy_orders_default = defineTool6({
  name: "list_pharmacy_orders",
  title: "\xD3rdenes de farmacia",
  description: "Lista \xF3rdenes de farmacia con sus items. Filtra por status o paciente.",
  inputSchema: {
    status: z5.string().optional().describe("Ej: pendiente | surtida | cancelada"),
    patient_id: z5.string().uuid().optional(),
    limit: z5.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, patient_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("pharmacy_orders").select("*, items:pharmacy_order_items(*)").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    if (patient_id) q = q.eq("patient_id", patient_id);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-estudios.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z6 } from "npm:zod@^4.4.3";
var list_estudios_default = defineTool7({
  name: "list_estudios",
  title: "Estudios solicitados",
  description: "Lista estudios de laboratorio/gabinete solicitados visibles para el usuario.",
  inputSchema: {
    status: z6.string().optional(),
    patient_id: z6.string().uuid().optional(),
    limit: z6.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, patient_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("estudios_solicitados").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("estatus", status);
    if (patient_id) q = q.eq("patient_id", patient_id);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/get-patient-summary.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z7 } from "npm:zod@^4.4.3";
var get_patient_summary_default = defineTool8({
  name: "get_patient_summary",
  title: "Resumen de paciente",
  description: "Devuelve perfil, \xFAltimas citas, medicamentos activos y alertas m\xE9dicas del paciente indicado (respeta RLS).",
  inputSchema: {
    patient_id: z7.string().uuid().describe("ID del paciente (por defecto el usuario conectado)").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ patient_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const pid = patient_id ?? ctx.getUserId();
    const [profile, appts, meds, alerts] = await Promise.all([
      sb.from("profiles").select("full_name,email,active_role").eq("user_id", pid).maybeSingle(),
      sb.from("appointments").select("id,appointment_date,appointment_type,doctor_name_manual,notes").eq("user_id", pid).order("appointment_date", { ascending: false }).limit(5),
      sb.from("medications").select("id,nombre,dosis,frecuencia,activo").eq("user_id", pid).eq("activo", true).limit(20),
      sb.from("medical_alerts").select("id,tipo,severidad,descripcion,activa").eq("patient_id", pid).eq("activa", true).limit(20)
    ]);
    const firstErr = [profile.error, appts.error, meds.error, alerts.error].find(Boolean);
    if (firstErr) return errorResult(firstErr.message);
    return jsonResult({
      patient_id: pid,
      profile: profile.data,
      recent_appointments: appts.data,
      active_medications: meds.data,
      active_alerts: alerts.data
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "zspetfkvdnhdbtcdwgry";
var mcp_default = defineMcp({
  name: "carecentral-mcp",
  title: "CareCentral MCP",
  version: "0.1.0",
  instructions: "Herramientas para CareCentral: expediente digital, recetas, farmacia (cat\xE1logo, inventario, \xF3rdenes) y estudios de laboratorio. Toda lectura respeta los permisos del usuario conectado (RLS). Empieza con `whoami` para conocer el rol y capacidades.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_recetas_default,
    get_receta_default,
    list_pharmacy_catalog_default,
    list_pharmacy_inventory_default,
    list_pharmacy_orders_default,
    list_estudios_default,
    get_patient_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
